export const rssFeeds = [
 ['BBC News · Top stories','BBC News','Top stories','https://feeds.bbci.co.uk/news/rss.xml'],
 ['BBC News · UK','BBC News','UK','https://feeds.bbci.co.uk/news/uk/rss.xml'],
 ['Sky News · UK','Sky News','UK','https://feeds.skynews.com/feeds/rss/uk.xml'],
 ['BBC News · World','BBC News','World','https://feeds.bbci.co.uk/news/world/rss.xml'],
 ['Sky News · World','Sky News','World','https://feeds.skynews.com/feeds/rss/world.xml'],
 ['BBC News · Technology','BBC News','Technology','https://feeds.bbci.co.uk/news/technology/rss.xml'],
 ['Sky News · Technology','Sky News','Technology','https://feeds.skynews.com/feeds/rss/technology.xml'],
 ['BBC News · Science & environment','BBC News','Science & nature','https://feeds.bbci.co.uk/news/science_and_environment/rss.xml'],
 ['BBC News · Business','BBC News','Business','https://feeds.bbci.co.uk/news/business/rss.xml'],
 ['Sky News · Business','Sky News','Business','https://feeds.skynews.com/feeds/rss/business.xml'],
 ['The Guardian · World','The Guardian','World','https://www.theguardian.com/world/rss'],
 ['Al Jazeera','Al Jazeera','World','https://www.aljazeera.com/xml/rss/all.xml'],
 ['France 24','France 24','World','https://www.france24.com/en/rss'],
 ['DW','DW','World','https://rss.dw.com/rdf/rss-en-all'],
 ['UN News','UN News','World','https://news.un.org/feed/subscribe/en/news/all/rss.xml'],
 ['AeroTime','AeroTime','Aviation','https://www.aerotime.aero/feed'],
 ['Aviation24.be','Aviation24.be','Aviation','https://www.aviation24.be/feed/'],
 ['The Aviationist','The Aviationist','Aviation','https://theaviationist.com/feed/'],
 ['Positive News','Positive News','Positive news','https://www.positive.news/feed/'],
 ['Good News Network','Good News Network','Positive news','https://www.goodnewsnetwork.org/feed/'],
 ['Reasons to be Cheerful','Reasons to be Cheerful','Positive news','https://reasonstobecheerful.world/feed/'],
 ['Mongabay','Mongabay','Science & nature','https://news.mongabay.com/feed/'],
 ['Smithsonian Magazine','Smithsonian Magazine','Science & nature','https://www.smithsonianmag.com/rss/latest_articles/'],
 ['FLYING Magazine','FLYING Magazine','Aviation','https://www.flyingmag.com/feed/'],
].map(([id,publisher,category,url])=>({id,publisher,category,url}));
