import assert from 'node:assert/strict';
import { reviewPatchTitles } from '../lib/jev.mjs';
import { writePatchTitles } from '../lib/patch-titles.mjs';
import { mergeEditions, validateArchive } from '../lib/edition-archive.mjs';
import { TITLE_STYLE_VERSION } from '../lib/editorial-policy.mjs';

const story={title:'New cat joins species roster',originalTitle:'Scientists discover a new cat species',note:'A new species was identified.',url:'https://example.org/cat',date:'2026-09-22',provider:'Example',publisher:'Example',category:'Science & nature',kind:'Added',worldwide:true,scopeReason:'New species expands scientific knowledge.',titleStyleVersion:TITLE_STYLE_VERSION,titleRevision:1};
const stories=[story,{...story,url:'https://example.org/local'},{...story,url:'https://example.org/prototype'},{...story,url:'https://example.org/excluded',worldwide:false}];
const probability=value=>({type:'boolean',probability:value});
let calls=0;
const response=(body,eligible=0.95,faithful=0.95)=>({answers:Object.fromEntries(Object.keys(body.questions).map(key=>[key,probability(key.startsWith('eligible')?eligible:faithful)]))});
const reviewed=await reviewPatchTitles(stories,{gatewayApiKey:'gateway-test',fetcher:async(url,options)=>{
 calls++;
 assert.equal(url,'https://ai-gateway.vercel.sh/v1/evaluate');
 assert.equal(options.headers.Authorization,'Bearer gateway-test');
 assert.ok(options.signal instanceof AbortSignal);
 const body=JSON.parse(options.body);
 assert.equal(body.model,'typesafe-ai/jev');
 assert.equal(body.state.length,3,'Groq rejections need no Jev request');
 assert.deepEqual(Object.keys(body.state[0]),['id','headline','patchTitle','kind']);
 assert.equal(Object.keys(body.questions).length,6);
 assert.ok(body.questions.eligible_0.instructions.includes('untrusted data'));
 assert.ok(body.questions.eligible_0.instructions.includes('not a collection of local stories'));
 assert.equal(body.providerOptions.gateway.zeroDataRetention,true);
 const result=response(body);
 result.answers.eligible_0=probability(0.8);
 result.answers.eligible_1=probability(0.79);
 result.answers.faithful_2=probability(0.2);
 return Response.json(result);
}});
assert.equal(calls,1);
assert.deepEqual(reviewed.map(a=>a.worldwide),[true,false,false,false]);
assert.equal(reviewed[3],stories[3]);
assert.equal(reviewed[0].url,story.url);
assert.match(reviewed[1].scopeReason,/eligibility/);
assert.match(reviewed[2].scopeReason,/accuracy/);
validateArchive(reviewed);
assert.throws(()=>validateArchive([{...story,jev:{model:'typesafe-ai/jev',eligibleProbability:'0.9',faithfulProbability:1}}]),/Invalid Jev/);
const revised={...reviewed[0],titleRevision:2};
assert.deepEqual(mergeEditions([story],[revised])[0].jev,revised.jev);
assert.deepEqual(mergeEditions([revised],[story])[0].jev,revised.jev);
await assert.rejects(reviewPatchTitles([story]),/not configured/);
for (const bad of [undefined,null,'0.9',-1,1.01,NaN]) {
 await assert.rejects(reviewPatchTitles([story],{gatewayApiKey:'test',fetcher:async()=>Response.json({answers:{eligible_0:probability(bad),faithful_0:probability(1)}})}),/Invalid Jev/);
}
for (const status of [401,429,503]) await assert.rejects(reviewPatchTitles([story],{gatewayApiKey:'test',fetcher:async()=>new Response('',{status})}),new RegExp(`HTTP ${status}`));
await assert.rejects(reviewPatchTitles([story],{gatewayApiKey:'test',fetcher:async()=>{throw new DOMException('Timed out','TimeoutError');}}),/Timed out/);
let batchCalls=0,signal;
await reviewPatchTitles(Array.from({length:25},()=>({...story})),{gatewayApiKey:'test',fetcher:async(_,options)=>{
 const body=JSON.parse(options.body);
 assert.equal(body.state.length,batchCalls++===0?24:1);
 if (signal) assert.equal(options.signal,signal,'All batches share one timeout');
 signal=options.signal;
 return Response.json(response(body));
}});
assert.equal(batchCalls,2);
const groqResult=()=>Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({entries:[{sourceId:0,title:story.title,kind:story.kind,worldwide:true,scopeReason:story.scopeReason}]})}}]});
const options={apiKey:'groq-test',gatewayApiKey:'gateway-test',fetcher:async(url,options)=>{
 if (url.startsWith('https://api.groq.com/')) return groqResult();
 return Response.json(response(JSON.parse(options.body),0.1));
}};
assert.equal((await writePatchTitles([story],options))[0].worldwide,false,'Shared writer must apply Jev');
const {getChangelog}=await import('../lib/changelog.mjs?jev-check');
const news={articles:[{...story,url:'https://example.org/new',originalTitle:'Scientists discover a new frog species'}],stale:[],unavailable:[]};
const failOptions={...options,archive:[{...story,date:'2026-09-21'}],fetcher:async url=>url.startsWith('https://api.groq.com/') ? groqResult() : new Response('',{status:503})};
await assert.rejects(getChangelog(news,{...failOptions,strict:true}),/Jev AI Gateway HTTP 503/);
assert.deepEqual((await getChangelog(news,failOptions)).articles,failOptions.archive,'Jev outage keeps the saved archive');
const {getChangelog:collect}=await import('../lib/changelog.mjs?jev-persist');
const result=await collect(news,{...options,strict:true});
assert.equal(result.articles[0].worldwide,false);
await collect(news,{...options,archive:result.articles,strict:true,fetcher:async()=>{throw Error('Saved rejections must not be reevaluated');}});
const {getChangelog:toggle}=await import('../lib/changelog.mjs?jev-enable');
assert.equal((await toggle(news,{...options,gatewayApiKey:'',strict:true})).articles[0].worldwide,true);
assert.equal((await toggle(news,{...options,strict:true})).articles[0].worldwide,false,'Enabling Jev must not reuse unchecked in-memory drafts');
console.log('Jev contract, thresholds, title checks, batch bounds, validation, archive retention and collection failure checks pass.');
