import { rssFeeds } from '../lib/rss-feeds.mjs';
import { parseRss, readFeed } from '../lib/rss.mjs';
import assert from 'node:assert/strict';
import { normalizeArticles, mergeArticles, getNews, sourceCount } from '../lib/news.mjs';
const now = Date.parse('2026-09-19T12:00:00Z');
const story = {title:'Scientists discover a new species',url:'https://example.org/discovery?utm_source=test',published_at:'2026-09-19T10:00:00Z',news_site:'Example'};
const normalized = normalizeArticles({results:[story,{...story,url:'javascript:alert(1)'},{...story,published_at:'2026-09-20T00:00:00Z'},{...story,published_at:'not-a-date'},{...story,published_at:'2025-01-01T00:00:00Z'}]},'Spaceflight News',now);
assert.equal(normalized.length,1);
assert.equal(normalized[0].url,'https://example.org/discovery');
assert.equal(normalized[0].kind,'Added');
assert.equal(normalizeArticles({results:[{...story,title:'APOD: A nice sky image'}]},'Spaceflight News',now).length,0);
assert.equal(normalizeArticles({articles:[{...story,title:'Planning applications this week',seendate:'20260918T091500Z'}]},'GDELT',now).length,0);
const indexed = normalizeArticles({articles:[{...story,seendate:'20260918T091500Z'}]},'GDELT',now);
assert.equal(indexed[0].dateLabel,'Indexed');
assert.equal(indexed[0].date,'2026-09-18T09:15:00.000Z');
assert.equal(mergeArticles([normalized,indexed]).length,1);
assert.throws(()=>normalizeArticles({error:'rate limited'},'GDELT',now));
let calls=0;
const success=async url=>{calls++;if(rssFeeds.some(feed=>feed.url===url))return new Response('<rss version="2.0"><channel><item><title>Scientists discover a new species</title><link>https://example.org/discovery</link><pubDate>Sat, 19 Sep 2026 10:00:00 GMT</pubDate></item></channel></rss>');return Response.json(url.includes('gdelt')?{articles:[{...story,seendate:'20260918T091500Z'}]}:{results:[{...story,title:'Rocket launch planned',url:'https://example.org/launch'}]});};
const [first,second]=await Promise.all([getNews(success,now),getNews(success,now)]);
assert.equal(calls,sourceCount);assert.deepEqual(first,second);assert.equal(first.articles.length,2);
await getNews(success,now+1_000);assert.equal(calls,sourceCount);
const failure=async()=>new Response('Unavailable',{status:503});
const stale=await getNews(failure,now+16*60_000);
assert.equal(stale.articles.length,2);assert.equal(stale.stale.length,sourceCount);
const expired=await getNews(failure,now+25*60*60_000);
assert.equal(expired.articles.length,0);assert.equal(expired.unavailable.length,sourceCount);
console.log('News validation, future-date filtering, deduplication, cache/coalescing and outage fallback pass.');


assert.equal(rssFeeds.length,24);
assert.equal(new Set(rssFeeds.map(feed=>feed.url)).size,24);
const feed=rssFeeds[0];
const rss='<rss version="2.0"><channel><item><title><![CDATA[New birds &amp; forests]]></title><link>https://example.org/birds</link><pubDate>Sat, 19 Sep 2026 10:00:00 GMT</pubDate></item></channel></rss>';
const records=parseRss(rss,feed);
assert.equal(records.length,1);assert.equal(records[0].title,'New birds & forests');
assert.equal(normalizeArticles({results:records},feed.id,now)[0].category,'Top stories');
const rdf='<rdf:RDF xmlns:rdf="urn:rdf" xmlns:dc="urn:dc"><item><title>Nature in the news</title><link>https://example.org/nature</link><dc:date>2026-09-19T10:00:00Z</dc:date></item></rdf:RDF>';
assert.equal(parseRss(rdf,feed)[0].published_at,'2026-09-19T10:00:00Z');
const atom='<feed xmlns="http://www.w3.org/2005/Atom"><entry><title>A new discovery &amp; more</title><link rel="self" href="https://example.org/api"/><link rel="alternate" href="/discovery"/><published>2026-09-19T10:00:00Z</published></entry></feed>';
assert.equal(parseRss(atom,feed)[0].url,'https://feeds.bbci.co.uk/discovery');
assert.equal(parseRss(atom,feed)[0].title,'A new discovery & more');
assert.throws(()=>parseRss('<html>Access denied</html>',feed));
assert.throws(()=>parseRss('<rss><channel></rss>',feed));
assert.throws(()=>parseRss('<!DOCTYPE rss [<!ENTITY x "boom">]><rss/>',feed));
assert.equal(await readFeed(new Response(rss)),rss);
await assert.rejects(()=>readFeed(new Response('x'.repeat(2*1024*1024+1))));
console.log('24 unique RSS feeds, RSS/Atom/RDF parsing, XML rejection and response-size limits pass.');

const summaryRecord=parseRss(rss.replace('</item>','<description><![CDATA[<p>Researchers restored <b>the forest</b> &amp; protected wildlife.</p>]]></description></item>'),feed)[0];
assert.equal(summaryRecord.summary,'Researchers restored the forest & protected wildlife.');
assert.equal(normalizeArticles({results:[summaryRecord]},feed.id,now)[0].summary,summaryRecord.summary);
assert.equal(normalizeArticles({results:[{...summaryRecord,summary:'x'.repeat(3000)}]},feed.id,now)[0].summary.length,1800);
console.log('Publisher story summaries survive RSS parsing and normalization as bounded plain text.');
